version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: sheet
      POSTGRES_DB: sheet
volumes:
  db: