import { Character } from '@prisma/client'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useForm } from 'react-hook-form'
import { Card } from '../../components/Card'
import { Layout } from '../../components/Layout'
import { prisma } from '../../lib/prisma'

export type EditIdProps = {
  character: Character
}

export default function EditId({ character }: EditIdProps) {
  const router = useRouter()
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<Character>({ defaultValues: character })
  const onSubmit = (data: Character) => {
    fetch(`/api/characters/${character.id}`, {
      body: JSON.stringify(data),
      headers: { 'Content-Type': 'application/json' },
      method: 'PUT',
    }).finally(() => {
      router.push('/list')
    })
  }

  return (
    <Layout>
      <>
        <Head>
          <title>Edit {character.name}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="flex h-full items-center justify-center">
          <Card className="w-full max-w-lg">
            <form onSubmit={handleSubmit(onSubmit)}>
              <div className="mb-6 grid gap-6 md:grid-cols-2">
                <div>
                  <label
                    htmlFor="name"
                    className="mb-2 block text-sm font-medium text-stone-900 dark:text-white"
                  >
                    Name
                  </label>
                  <input
                    type="text"
                    id="name"
                    className="block w-full rounded-lg border border-stone-300 bg-stone-50 p-2.5 text-sm text-stone-900 focus:border-emerald-500 focus:ring-emerald-500 dark:border-stone-600 dark:bg-stone-700 dark:text-white dark:placeholder:text-stone-400 dark:focus:border-emerald-500 dark:focus:ring-emerald-500"
                    {...register('name', { required: true })}
                  />
                </div>
                <div>
                  <label
                    htmlFor="class"
                    className="mb-2 block text-sm font-medium text-stone-900 dark:text-white"
                  >
                    Klasse
                  </label>
                  <input
                    type="text"
                    id="class"
                    value={character.class}
                    className="block w-full rounded-lg border border-stone-300 bg-stone-50 p-2.5 text-sm text-stone-900 focus:border-emerald-500 focus:ring-emerald-500 dark:border-stone-600 dark:bg-stone-700 dark:text-white dark:placeholder:text-stone-400 dark:focus:border-emerald-500 dark:focus:ring-emerald-500"
                    {...register('class', { required: true })}
                  />
                </div>
              </div>
              <button
                type="submit"
                className="w-full rounded-lg bg-emerald-700 px-5 py-2.5 text-center text-sm font-medium text-white hover:bg-emerald-800 focus:outline-none focus:ring-4 focus:ring-emerald-300 dark:bg-emerald-600 dark:hover:bg-emerald-700 dark:focus:ring-emerald-800 sm:w-auto"
              >
                Speichern
              </button>
            </form>
          </Card>
        </main>

        <footer></footer>
      </>
    </Layout>
  )
}

export const getServerSideProps: GetServerSideProps<
  { character: Character | null },
  { id: string }
> = async ({ params }) => {
  const character = await prisma.character.findUnique({
    where: { id: params?.id },
  })

  return {
    props: {
      character,
    },
  }
}
