import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import { Layout } from '../components/Layout'

export default function Home() {
  const router = useRouter()
  useEffect(() => {
    router.push('/list')
  })

  return (
    <Layout>
      <>
        <Head>
          <title>Charakter Sheets</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main></main>

        <footer></footer>
      </>
    </Layout>
  )
}
