import Head from 'next/head'
import { prisma } from '../lib/prisma'
import { Layout } from '../components/Layout'
import { Character } from '@prisma/client'
import { GetServerSideProps } from 'next'
import {
  PencilIcon,
  TrashIcon,
  EyeIcon,
  UserIcon,
} from '@heroicons/react/20/solid'
import { Card } from '../components/Card'
import { useRouter } from 'next/router'

export type ListProps = {
  characters: Character[]
}

export default function List({ characters }: ListProps) {
  const router = useRouter()
  const handleDelete = (id: Character['id']) =>
    fetch(`api/characters/${id}`, {
      headers: { 'Content-Type': 'application/json' },
      method: 'DELETE',
    }).then(() => refreshData())
  const refreshData = () => {
    router.replace(router.asPath)
  }
  return (
    <Layout>
      <>
        <Head>
          <title>Charakter Sheet List</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="flex h-full items-center justify-center">
          <Card className="w-full max-w-lg">
            <ul
              role="list"
              className="divide-y divide-gray-200 dark:divide-gray-700"
            >
              {characters.map((character) => (
                <li className="py-3 sm:py-4" key={character.id}>
                  <div className="flex items-center space-x-4">
                    <div className="shrink-0">
                      <UserIcon className="h-8 w-8" />
                    </div>
                    <div className="min-w-0 flex-1">
                      <p className="truncate text-sm font-medium text-gray-900 dark:text-white">
                        {character.name}
                      </p>
                      <p className="truncate text-sm text-gray-500 dark:text-gray-400">
                        {character.class}
                      </p>
                    </div>
                    <div className="flex flex-row space-x-2">
                      <a
                        href={`edit/${character.id}`}
                        className="flex h-7 w-7 items-center justify-center rounded-lg bg-stone-600 text-xs font-medium text-white"
                      >
                        <PencilIcon className="h-4 w-4" />
                      </a>
                      <button
                        onClick={() => handleDelete(character.id)}
                        className="flex h-7 w-7 items-center justify-center rounded-lg bg-stone-600 text-xs font-medium text-white"
                      >
                        <TrashIcon className="h-4 w-4" />
                      </button>
                      <a
                        href={`edit/${character.id}`}
                        className="flex h-7 w-7 items-center justify-center rounded-lg bg-stone-600 text-xs font-medium text-white"
                      >
                        <EyeIcon className="h-4 w-4" />
                      </a>
                    </div>
                  </div>
                </li>
              ))}
            </ul>
          </Card>
        </main>

        <footer></footer>
      </>
    </Layout>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  // READ all notes from DB
  const characters = await prisma.character.findMany()

  return {
    props: {
      characters,
    },
  }
}
